### ISSUE TITLE
Battlefield V RPC not updating

### ISSUE THREAD

**Issue by MG665** [community-network/Battlefield-rich-presence#3]
The Battlefield V Rich Presence is not updating after joining any server, just stays "In the menus"
![image](https://user-images.githubusercontent.com/13345045/194782738-189f551b-ecb4-45f3-a2d9-99b362c01516.png)
Battlefield 1 & 4 works correctly.

**Comment by MG665** [comment]
![image](https://user-images.githubusercontent.com/13345045/194782877-9b420e7a-1bde-4dea-a9a1-b1f7e0ff073d.png)

**Comment by cetteup** [comment]
Could you provide a link to your BF5 stats profile?

**Comment by MG665** [comment]
> Could you provide a link to your BF5 stats profile?

https://battlefieldtracker.com/bfv/profile/origin/MedGr450/overview

**Comment by cetteup** [comment]
The screenshot shows "GG" instead as the configured name, was that just entered to now show your player name in the screenshot?

**Comment by MG665** [comment]
> The screenshot shows "GG" instead as the configured name, was that just entered to now show your player name in the screenshot?

Actually I tried the name again and it worked! I had a caps typo, it was MedGR450 instead of the correct MedGr450
![image](https://user-images.githubusercontent.com/13345045/194914496-02613bf7-6798-48b8-afa4-f1a3314c877f.png)
Thank you for the tip!
