### ISSUE TITLE
Battlefield Rich Presence is not using the latest version of GameDataReader

### ISSUE THREAD

**Issue by AnomalousNicole** [community-network/Battlefield-rich-presence#6]
Last week, I opened a pull request so that Battlefield Rich Presence would use the latest version of GameDataReader (0.0.4).  However today, I noticed that the 1.4.7 Release build of Battlefield Rich Presence was not working correctly with Discord.  The 1.4.7 build of Battlefield Rich Presence exhibits the same behavior as the previous versions.  I looked at the install directory for Battlefield Rich Presence and it appears that it is using version 0.0.2 of GameDataReader based on the timestamp of the DLL file and the release date of GameDataReader 0.0.2.

I was able to fix the issue by building the Battlefield Rich Presence solution locally and then installing the 1.4.7 Debug build of Battlefield Rich Presence.  I have attached screenshots showing the timestamp of the GameDataReader DLL when the Debug and Release versions are installed.  It appears that the Battlefield rich presence.csproj project file is setup to use the correct version of GameDataReader, so I am not sure where the issue lies.

1.4.7 Debug Build:
![Battlefield Rich Presence_Debug_Build_1 4 7](https://user-images.githubusercontent.com/481352/226222062-bbaa94f3-a8ed-4239-9c90-7a29ad8f8743.jpg)

1.4.7 Release Build:
![Battlefield Rich Presence_Release_Build_1 4 7](https://user-images.githubusercontent.com/481352/226222063-815a4af6-1851-4e88-b4d3-a5703183d5eb.jpg)

**Comment by zefanjajobse** [comment]
rebuilding 1.4.7 as 1.4.8, apparently I forgot to pull before making release tag... https://github.com/community-network/Battlefield-rich-presence/actions/runs/4466116786/jobs/7843899822

**Comment by AnomalousNicole** [comment]
@zefanjajobse Thank you for creating a new release build.  I installed 1.4.8 and it appears that Battlefield Rich Presence is now using the 0.0.4 version of GameDataReader.  I tested the new build with BF1942 and my game information showed up in Discord correctly.  I would say that this issue can be closed.
